login:
  path: /login
  defaults: { _controller: PicBundle:User:login }

login_check:
  path: /login_check

logout:
  path: /logout

pic_homepage:
    path:     /
    defaults: { _controller: PicBundle:Post:list }

pic_tags:
    path:     /tag/add
    defaults: { _controller: PicBundle:Tag:create }

post_add:
  path: /add
  defaults: { _controller: PicBundle:Post:add }
