login:
    path:     /login
    defaults: { _controller: PicBundle:User:login }

login_check:
    path:     /login_check

logout:
    path:     /logout

pic_homepage:
    path:     /
    defaults: { _controller: PicBundle:Post:list }

pic_tags:
    path:     /tag/add
    defaults: { _controller: PicBundle:Tag:create }
pic_tags_delete:
    path:     /tag/delete/{id}
    defaults: { _controller: PicBundle:Tag:delete }

post_add:
  path: /add
  defaults: { _controller: PicBundle:Post:add }

post_ajax:
  path: /add/ajax
  defaults: { _controller: PicBundle:Post:addAjax }

post_detail:
  path: /post/{postId}
  defaults: { _controller: PicBundle:Post:detail }
  requirements:
        page: '\d+'
post_tag:
  path: /add/tag
  defaults: { _controller: PicBundle:Post:addTag }

post_comment:
  path: /add/comment
  defaults: { _controller: PicBundle:Comment:add }


post_rating:
  path: /add/rating
  defaults: { _controller: PicBundle:Rating:add }

rating_count:
  path: /rating/count/{id}
  defaults: { _controller: PicBundle:Rating:count }

comment_count:
  path: /comment/count/{id}
  defaults: { _controller: PicBundle:Comment:count }

user_me:
  path: /me
  defaults: { _controller: PicBundle:User:me }

user_profile:
  path: /user/{id}
  defaults: { _controller: PicBundle:User:detail }

follow:
  path: /follow/{id}
  defaults: { _controller: PicBundle:Follower:follow }
