login:
  path: /login
  defaults: { _controller: PicBundle:User:login }

login_check:
  path: /login_check

logout:
  path: /logout

pic_homepage:
    path:     /
    defaults: { _controller: PicBundle:Post:list }

pic_tags:
    path:     /tag/add
    defaults: { _controller: PicBundle:Tag:create }
pic_tags_delete:
    path:     /tag/delete/{id}
    defaults: { _controller: PicBundle:Tag:delete }

post_add:
  path: /add
  defaults: { _controller: PicBundle:Post:add }

post_ajax:
  path: /add/ajax
  defaults: { _controller: PicBundle:Post:addAjax }

post_detail:
  path: /post/{postId}
  defaults: { _controller: PicBundle:Post:detail }
  requirements:
        page: '\d+'
post_tag:
  path: /add/tag
  defaults: { _controller: PicBundle:Post:addTag }
