login:
    path:     /login
    defaults: { _controller: PicBundle:User:login }

login_check:
    path:     /login_check

logout:
    path:     /logout

pic_homepage:
    path:     /{page}
    defaults: { _controller: PicBundle:Post:list, page:1 }
    requirements:
          page: '\d+'

pic_tags:
    path:     /tag/add
    defaults: { _controller: PicBundle:Tag:create }
pic_tags_delete:
    path:     /tag/delete/{id}
    defaults: { _controller: PicBundle:Tag:delete }

post_add:
  path: /add
  defaults: { _controller: PicBundle:Post:add }

post_ajax:
  path: /add/ajax
  defaults: { _controller: PicBundle:Post:addAjax }

post_detail:
  path: /post/{postId}
  defaults: { _controller: PicBundle:Post:detail }
  requirements:
        postId: '\d+'
post_tag:
  path: /add/tag
  defaults: { _controller: PicBundle:Post:addTag }

post_comment:
  path: /add/comment
  defaults: { _controller: PicBundle:Comment:add }

post_visibility:
  path: /post/{id}/visibility
  defaults: { _controller: PicBundle:Post:visibility }

post_delete:
  path: /post/{id}/delete
  defaults: { _controller: PicBundle:Post:delete }

post_fav:
  path: /post/{id}/fav
  defaults: { _controller: PicBundle:Post:fav }
post_query:
  path: /post/list
  defaults: { _controller: PicBundle:Post:query }

post_rating:
  path: /add/rating
  defaults: { _controller: PicBundle:Rating:add }

rating_count:
  path: /rating/count/{id}
  defaults: { _controller: PicBundle:Rating:count }

comment_count:
  path: /comment/count/{id}
  defaults: { _controller: PicBundle:Comment:count }

user_me:
  path: /me
  defaults: { _controller: PicBundle:User:me }

user_profile:
  path: /user/{id}
  defaults: { _controller: PicBundle:User:detail }
  requirements:
    id: '\d+'

user_edit_name:
  path: /user/name
  defaults: { _controller: PicBundle:User:name }

user_edit_visibility:
  path: /user/visibility
  defaults: { _controller: PicBundle:User:visibility }

user_activate:
  path: /user/activate/{token}
  defaults: { _controller: PicBundle:User:activate }

follow:
  path: /follow/{id}
  defaults: { _controller: PicBundle:Follower:follow }
  requirements:
        id: '\d+'
follow_list:
  path: /follow/list/{id}
  defaults: { _controller: PicBundle:Follower:list }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
