# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    access_denied_url: /
    encoders:
        PicBundle\Entity\User:
            algorithm: bcrypt
            cost: 4

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: PicBundle:User
                property: mail

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/login, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/tag/add, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/tag/delete/\d+, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/add, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/add/ajax, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/tag/tag, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/tag/comment, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/post/\d+/visibility, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/post/\d+/delete, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/post/\d+/fav, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/add/rating, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/comment/count/\d+, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/me, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/user/\d+, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/user/name, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/user/visibility, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/follow/\d+, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/follow/list/\d+, roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: ^/admin, roles: ROLE_ADMIN}


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
