PicBundle\Entity\Comment:
    type: entity
    table: comments
    indexes:
        fk_user:
            columns:
                - user_id
        fk_post:
            columns:
                - post_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        content:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        inserteddate:
            type: date
            nullable: true
            column: insertedDate
    manyToOne:
        post:
            targetEntity: Post
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: postComments
            joinColumns:
                post_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: userComment
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
