PicBundle\Entity\Post:
    type: entity
    table: posts
    repositoryClass: PicBundle\Repository\PostRepository
    indexes:
        fk_post_users:
            columns:
                - author_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        inserteddate:
            type: date
            nullable: true
            column: insertedDate
        updateddate:
            type: date
            nullable: true
            column: updatedDate
        status:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
        location:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
        type:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
    manyToOne:
        author:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: userPost
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
      postTags:
        targetEntity: PostTag
        mappedBy: tag
        cascade: ["persist"]
      postRatings:
        targetEntity: Rating
        mappedBy: post
        cascade: ["persist"]
      postComments:
        targetEntity: Comment
        mappedBy: post
        cascade: ["persist"]
      postFavs:
        targetEntity: Fav
        mappedBy: post
        cascade: ["persist"]
    lifecycleCallbacks: {  }
