PicBundle\Entity\Tag:
    type: entity
    table: tags
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
    oneToMany:
      tagPosts:
        targetEntity: PostTag
        mappedBy: tag
        cascade: ["persist"]
    lifecycleCallbacks: {  }
